### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by tbenavi1** [refresh-bio/KMC#216]
Hello,

It is not a pressing issue but I just wanted you to be aware that KMC currently doesn't compile with Python 3.11. I receive the following error:

```
py_kmc_api/libs/pybind11/include/pybind11/pybind11.h:2026:52: error: invalid use of incomplete type ‘PyFrameObject’ {a
ka ‘struct _frame’}
```

I believe the issue is that PyFrameObject has changed as documented in https://docs.python.org/3.11/whatsnew/3.11.html.
